### ISSUE TITLE
Add support for Content-Type: application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by Gen3ddd** [kajf/bozr#117]
need to add support for Content-Type: application/x-www-form-urlencoded
Right now OAuth2.0 is developing in the project and for this purpose we need this support, please find link below
https://www.rfc-editor.org/rfc/rfc6749#page-74

**Comment by kajf** [comment]
I am not sure I understand what is not supported. 
Did you try passing this header, e.g.
```
{
  "on": {
    "method": "POST",
    "url": "/api/company/users",
    "headers": {
        "Content-Type": "application/x-www-form-urlencoded"
    },
    "bodyFile" : "body.txt"
  }
}
```
Can you provide the suite.json example which is not working for you?

**Comment by Gen3ddd** [comment]
{
        "on": {
          "method": "POST",
          "url": "/rest/v2/companies/666027/oauth2/token",
          "headers": {
            "Accept": "application/json",
            "Content-Type": "application/x-www-form-urlencoded"
          },
          "bodyFile": "body.json"
        },
        "expect": {
          "statusCode": 200
          }
        }
      }

**Comment by Gen3ddd** [comment]
![image](https://user-images.githubusercontent.com/25951495/190601880-9b29c550-eb5b-48e1-9ee9-84a9065f0e90.png)

**Comment by Gen3ddd** [comment]
From POST:
![image](https://user-images.githubusercontent.com/25951495/190602546-f3b8438c-1596-40c3-a59e-042e9eac01ab.png)

**Comment by kajf** [comment]
I think the issue is not in content type support rather in body you are trying to send.
body file should not be a json, rather a urlencoded string like in url params, e.g. field1=value1&field2=value2

see example
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST#example

**Comment by Gen3ddd** [comment]
You are right, sorry for the disturbing.Thanks a lot!
