### ISSUE TITLE
"Cannot parse file" error is failing silently on the top of the log

### ISSUE THREAD

**Issue by kajf** [kajf/bozr#23]
Need a way of informing about invalid suits (e.g. create invalid test result)

**Comment by dpfg** [comment]
Invalid test result is not valid way to notify users as there is no test actually. 
I thought about adding non-zero exit code if failed to parse at least on file. Additionally we can add summary about invalid files.

**Comment by darkowl91** [comment]
Invalid suite can be marked as skipped.

**Comment by dpfg** [comment]
Validation of all suite files has been added as a required step before run steps. If at least one suite file is invalid - tests will not run.
