### ISSUE TITLE
Introduce feature to avoid call per time number limitations

### ISSUE THREAD

**Issue by maksimkarnitski** [kajf/bozr#51]
Some APIs has call per second limitation that cannot be changed. For example, there are 6 bozr tests with 7 calls. Two tests fail with the response 503 "You have exceeded the API rate limit of 5 requests per second".

I would suggest to add "waiter" feature that could be set on test level and allows to specify delay before test execution in seconds.

**Comment by dpfg** [comment]
A temporary workaround is to have a simple endpoint that holds connection for defined amount of time.
```
GET /your-api/wait?duration=5m
```
