### ISSUE TITLE
Make failed calls identifiable

### ISSUE THREAD

**Issue by AlexanderTrygub** [kajf/bozr#54]
_**Enhancement.**_
To create data independent test-scenarios we need to use arguments, but they are working only in borders of particular test. 
Thus, we use a numerous calls in the one test, but they are not represented in the log-monitor of test running. So it makes complications with troubleshooting during the test-scenario creating. Sometimes it's rather difficult to find out in which call is a problem, if test is failed, .
We can use option -i, but in this case log-monitor contains a lot of redundant information.
That's why it would be great to add optional parameter 'Name' to the calls. It could be used only if needed. In this case log-monitor should represent not only running tests, but also the calls they consist.

**Comment by dpfg** [comment]
It's a bit cumbersome to give a name to each call. Index of the call should be good enough. @kajf  thoughts?

**Comment by kajf** [comment]
Adding call index to report instead of name makes perfect sense to me.
