### ISSUE TITLE
Simulate a back end with mock servers

### ISSUE THREAD

**Issue by darkowl91** [kajf/bozr#55]
Throughout the development process, delays on the front end or back end can hold up dependent teams from completing their work efficiently.  

Using mock servers, developers can simulate each endpoint to view the potential responses, without actually spinning up a back end.

**Comment by dpfg** [comment]
Bozr is a quite simple tool with one responsibility - test REST API. Mocking server requires an expressive declarative description of API. Test suites by definition cannot replace API description.
