### ISSUE TITLE
Ability to generate tests documentation 

### ISSUE THREAD

**Issue by darkowl91** [kajf/bozr#56]
Generates and hosts browser-based documentation for the test suites automatically in real-time. 

Documentation for test includes the following:
* Sample requests, headers, and other metadata
* Descriptions associated with requests, folders, and test suites

Documentation can be published to a server which will allow to keep in sync dev and qa teams. 
In addition this will allow to manage tests more effectively.

**Comment by dpfg** [comment]
Test suites in JSON format are playing a role of test documentation. Could you elaborate why would you need have description of tests in another format?
