### ISSUE TITLE
Windows bin in all released archives

### ISSUE THREAD

**Issue by okoreniuk** [kajf/bozr#63]
Hi
you have the same windows binary file in all archives since 0.8.4

MD5:a04c82d0bc302b7cfe83c27f2cf1263f  bozr.darwin
MD5:a04c82d0bc302b7cfe83c27f2cf1263f  bozr.exe
MD5:a04c82d0bc302b7cfe83c27f2cf1263f  bozr.linux

"MZ<90>^@^C^@^D^@^@^@^@^@<FF><FF>^@^@<8B>^@^@^@^@^@^@^@@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@<80>^@^@^@^N^_<BA>^N^@<B4> <CD>!<B8>^AL<CD>!This program cannot be run in DOS mode."

**Comment by dpfg** [comment]
Thanks for reporting this!
I've release new binaries for v0.8.11. @okoreniuk could you try it?
Also I've removed non-windows build for previous releases to avoid confusion.
