### ISSUE TITLE
Add ability to refer to used Host in a test case

### ISSUE THREAD

**Issue by dpfg** [kajf/bozr#87]
If test case need to be aware of environment we are currently using to run (-H) there is no way except of hardcoding or using env variable right now. Hardcoding is not an option. Environment variable requires preconfiguration and reduces re-runnability of test cases on local env.

Viable option could be to automatically add host parameter to the list of environment variables. This makes it easier to run comparing to pure env. var but still allow to parameterize tests. 

```
"parameters": {
  "node": "{env:HOST}"
}
```

**Comment by dpfg** [comment]
@kajf thoughts?

**Comment by kajf** [comment]
fine by me, just need to come up with good prefix (don't overlap with env variables)
maybe
```
"parameters": {
  "node": "{glob:HOST}"
}
```
or use env, but have more unique name then just HOST
